import {CourierInfo, ValidationRule} from '../types';

// ─── 快递公司单号规则 ───────────────────────────────────────────────────────────
export const COURIER_RULES: {pattern: RegExp; info: CourierInfo}[] = [
  {
    pattern: /^SF\d{12}$|^\d{12}$(?=.*SF)/i,
    info: {company: '顺丰速运', companyEn: 'SF Express', color: '#E60012'},
  },
  {
    pattern: /^SF\d{15}$/i,
    info: {company: '顺丰速运', companyEn: 'SF Express', color: '#E60012'},
  },
  {
    pattern: /^75\d{11}$|^77\d{11}$|^78\d{11}$/,
    info: {company: '顺丰速运', companyEn: 'SF Express', color: '#E60012'},
  },
  {
    pattern: /^JD\d{13}$/i,
    info: {company: '京东物流', companyEn: 'JD Logistics', color: '#E1251B'},
  },
  {
    pattern: /^[A-Z]{2}\d{9}[A-Z]{2}$/,
    info: {company: '邮政EMS', companyEn: 'China EMS', color: '#006A00'},
  },
  {
    pattern: /^60\d{10}$|^30\d{10}$/,
    info: {company: '中通快递', companyEn: 'ZTO Express', color: '#E6A817'},
  },
  {
    pattern: /^70\d{10}$|^773\d{9}$/,
    info: {company: '圆通速递', companyEn: 'YTO Express', color: '#00A0E9'},
  },
  {
    pattern: /^268\d{9}$|^888\d{9}$|^366\d{9}$/,
    info: {company: '韵达快递', companyEn: 'Yunda Express', color: '#FFC000'},
  },
  {
    pattern: /^4[56]\d{10}$|^268\d{9}$/,
    info: {company: '申通快递', companyEn: 'STO Express', color: '#6CBF66'},
  },
  {
    pattern: /^3\d{11}$|^1\d{11}$/,
    info: {company: '百世快递', companyEn: 'Best Express', color: '#FF6600'},
  },
  {
    pattern: /^DB\d{11}$/i,
    info: {company: '德邦物流', companyEn: 'Deppon', color: '#E50012'},
  },
  {
    pattern: /^9\d{17}$/,
    info: {company: '极兔速递', companyEn: 'J&T Express', color: '#FF0000'},
  },
];

// ─── 默认防呆验证规则 ──────────────────────────────────────────────────────────
export const DEFAULT_VALIDATION_RULES: ValidationRule[] = [
  {
    id: 'courier',
    name: '快递单号',
    nameEn: 'Tracking Number',
    pattern: '',
    enabled: false,
  },
  {
    id: 'barcode_13',
    name: 'EAN-13商品码',
    nameEn: 'EAN-13 Barcode',
    pattern: '^\\d{13}$',
    enabled: false,
  },
  {
    id: 'barcode_8',
    name: 'EAN-8商品码',
    nameEn: 'EAN-8 Barcode',
    pattern: '^\\d{8}$',
    enabled: false,
  },
  {
    id: 'custom',
    name: '自定义规则',
    nameEn: 'Custom Rule',
    pattern: '',
    enabled: false,
  },
];

// ─── 多语言文本 ────────────────────────────────────────────────────────────────
export const I18N = {
  zh: {
    appName: 'PDA 扫码助手',
    startScan: '开始扫码',
    scanMode: '扫码模式',
    ocrMode: 'OCR文字识别',
    records: '扫码记录',
    settings: '设置',
    total: '总计',
    unique: '不重复',
    types: '码类型',
    synced: '已同步',
    unsynced: '待同步',
    copy: '复制',
    copied: '已复制',
    delete: '删除',
    clearAll: '清空',
    exportExcel: '导出Excel',
    exportCSV: '导出CSV',
    confirmClear: '确认清空',
    confirmClearMsg: '将删除全部扫码记录，确定继续？',
    cancel: '取消',
    confirm: '确定',
    searchPlaceholder: '搜索扫码内容...',
    wifiConfig: 'WiFi传输配置',
    wifiEnabled: '开启WiFi传输',
    wifiIP: '电脑IP地址',
    wifiPort: '端口号',
    wifiSuffix: '追加字符',
    connected: '已连接',
    disconnected: '未连接',
    connecting: '连接中',
    offlineQueue: '离线队列',
    offlineCount: '待上传',
    uploadAll: '全部上传',
    uploadSuccess: '上传成功',
    uploadFail: '上传失败',
    validationPass: '验证通过',
    validationFail: '验证失败',
    courier: '快递识别',
    sound: '扫码提示音',
    vibration: '震动反馈',
    duplicateCheck: '防重复扫描',
    autoUpload: 'WiFi恢复自动上传',
    validationRules: '防呆验证规则',
    language: '语言',
    scanTip: '将条码/二维码对准框内',
    ocrTip: '将文字区域对准框内识别',
    torch: '手电筒',
    waitScan: '等待扫码...',
    lastResult: '最新结果：',
    scanned: '已扫',
    items: '条',
    noRecords: '暂无扫码记录',
    tapToScan: '点击下方按钮开始扫码',
    export: '导出',
    exportSuccess: '导出成功',
    noData: '暂无数据可导出',
    ruleEnabled: '已启用规则',
    ruleDisabled: '未启用规则',
    enterIP: '请输入电脑IP',
    enterPort: '请输入端口',
    testConnect: '测试连接',
    connectOk: '连接成功！',
    connectFail: '连接失败，请检查IP和端口',
    cooldown: '扫码冷却(ms)',
    duplicateWindow: '重复检测时间',
    duplicateWindowDesc: '同一条码在此时间内不允许重复录入',
    dupOff: '关闭（允许重复）',
    dup12h: '12 小时',
    dup24h: '24 小时',
    dup48h: '48 小时',
    dupWeek: '一 周',
    dupMonth: '一 个 月',
    dupForever: '永 久',
    duplicateTitle: '重复条码',
    duplicateMsg: (value: string, time: string) =>
      `"${value}"\n已于 ${time} 录入过`,
    duplicateIgnore: '忽略',
    duplicateForce: '强制录入',
    // 云存储 / 拍照上传
    cloudConfig: '云存储配置',
    photoEnabled: '扫码同时拍照上传',
    cloudEnabled: '开启云上传',
    cloudUrl: '上传接口URL',
    cloudToken: '认证Token（Bearer）',
    cloudFieldName: '文件字段名',
    cloudExtraParams: '额外参数（JSON）',
    cloudUrlPlaceholder: 'https://your-api.com/upload',
    cloudFieldPlaceholder: 'file',
    cloudExtraPlaceholder: '{"bucket":"scanner"}',
    testCloudUpload: '测试上传',
    cloudUploadOk: '云上传测试成功！',
    cloudUploadFail: '云上传失败，请检查配置',
    photoUploaded: '照片已上传',
    photoPending: '待上传',
    photoNone: '无照片',
    cloudEnterUrl: '请输入上传接口URL',
  },
  en: {
    appName: 'PDA Scanner',
    startScan: 'Start Scan',
    scanMode: 'Barcode Scan',
    ocrMode: 'OCR Recognition',
    records: 'Records',
    settings: 'Settings',
    total: 'Total',
    unique: 'Unique',
    types: 'Types',
    synced: 'Synced',
    unsynced: 'Pending',
    copy: 'Copy',
    copied: 'Copied',
    delete: 'Del',
    clearAll: 'Clear',
    exportExcel: 'Export Excel',
    exportCSV: 'Export CSV',
    confirmClear: 'Confirm Clear',
    confirmClearMsg: 'All records will be deleted. Continue?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    searchPlaceholder: 'Search records...',
    wifiConfig: 'WiFi Transfer Config',
    wifiEnabled: 'Enable WiFi Transfer',
    wifiIP: 'Computer IP',
    wifiPort: 'Port',
    wifiSuffix: 'Append Char',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connecting: 'Connecting',
    offlineQueue: 'Offline Queue',
    offlineCount: 'Pending Upload',
    uploadAll: 'Upload All',
    uploadSuccess: 'Upload OK',
    uploadFail: 'Upload Failed',
    validationPass: 'Pass',
    validationFail: 'Failed',
    courier: 'Courier',
    sound: 'Sound',
    vibration: 'Vibration',
    duplicateCheck: 'Anti-Duplicate',
    autoUpload: 'Auto Upload on WiFi',
    validationRules: 'Validation Rules',
    language: 'Language',
    scanTip: 'Align barcode/QR code in frame',
    ocrTip: 'Align text area in frame',
    torch: 'Torch',
    waitScan: 'Waiting for scan...',
    lastResult: 'Last: ',
    scanned: 'Scanned',
    items: '',
    noRecords: 'No records yet',
    tapToScan: 'Tap button below to start',
    export: 'Export',
    exportSuccess: 'Exported!',
    noData: 'No data to export',
    ruleEnabled: 'Rule enabled',
    ruleDisabled: 'No rule',
    enterIP: 'Enter computer IP',
    enterPort: 'Enter port',
    testConnect: 'Test',
    connectOk: 'Connected!',
    connectFail: 'Failed, check IP & port',
    cooldown: 'Cooldown (ms)',
    duplicateWindow: 'Duplicate Window',
    duplicateWindowDesc: 'Same barcode not allowed within this period',
    dupOff: 'Off (Allow duplicates)',
    dup12h: '12 Hours',
    dup24h: '24 Hours',
    dup48h: '48 Hours',
    dupWeek: '1 Week',
    dupMonth: '1 Month',
    dupForever: 'Forever',
    duplicateTitle: 'Duplicate Barcode',
    duplicateMsg: (value: string, time: string) =>
      `"${value}"\nwas scanned at ${time}`,
    duplicateIgnore: 'Ignore',
    duplicateForce: 'Force Add',
    // Cloud storage / photo upload
    cloudConfig: 'Cloud Storage',
    photoEnabled: 'Photo Upload on Scan',
    cloudEnabled: 'Enable Cloud Upload',
    cloudUrl: 'Upload API URL',
    cloudToken: 'Auth Token (Bearer)',
    cloudFieldName: 'File Field Name',
    cloudExtraParams: 'Extra Params (JSON)',
    cloudUrlPlaceholder: 'https://your-api.com/upload',
    cloudFieldPlaceholder: 'file',
    cloudExtraPlaceholder: '{"bucket":"scanner"}',
    testCloudUpload: 'Test Upload',
    cloudUploadOk: 'Cloud upload test succeeded!',
    cloudUploadFail: 'Upload failed, check config',
    photoUploaded: 'Photo uploaded',
    photoPending: 'Pending',
    photoNone: 'No photo',
    cloudEnterUrl: 'Please enter upload API URL',
  },
};
